---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"
  push:

jobs:
  unit-tests-master:
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: unit-tests-master
            env:
              DOKKU_VERSION: master
          - name: unit-tests-0.19.0
            env:
              DOKKU_TAG: v0.19.0

    name: unit-tests-${{ matrix.name }}
    runs-on: ubuntu-22.04

    steps:
      - name: Add dokku version to environment
        run: echo "DOKKU_VERSION=${{ matrix.env.DOKKU_VERSION }}" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: "3.7.x"

      - run: make setup

      - run: sudo sysctl -w vm.max_map_count=262144

      - run: |
          git fetch -q origin main
          changed=$(git --no-pager diff --name-only $GITHUB_SHA..origin/main)
          if [ $changed = "Dockerfile" ]; then
            echo "Please run 'make generate' to update the image version in the README.md"
          else
            make generate
            if ! git diff --quiet README.md; then
              echo "Please run 'make generate'"
              git status --short
              git --no-pager diff README.md
              exit 1
            fi
          fi

      - run: make test

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: tmp/test-results
          path: test-results
